### ISSUE TITLE
installation / startup help

### ISSUE THREAD

**Issue by aryairani** [unisonweb/codebase-ui#25]
Hi, I'm having some trouble getting started.

The README.md says:
```
Start ucm and copy the API URL and API Token (this URL is uniquely generated by ucm at start-up) from the ucm start-up output (It's formatted as a single URL with a query string. Get the token by from the query string).

Then start the development server, run:

    API_URL="<API URL FROM UCM>" API_TOKEN="<API TOKEN FROM UCM>" npm start

Then visit http://localhost:8000 to use the UI.
```

So:
```
arya@jrrr unison-trunk % stack exec unison

  I've started a codebase API server at 


  http://127.0.0.1:55484?X%2FkGfCrT2RUerJpU0x6bibwQsA0410dv
```

I'm guessing everything before the `?` is the URL and everything after it is the TOKEN?  But I'm not too confident.
```
arya@jrrr codebase-ui % API_URL="http://127.0.0.1:55484" API_TOKEN="X%2FkGfCrT2RUerJpU0x6bibwQsA0410dv" npm start

> codebase-ui@1.0.0 start
> npm run makeElmEnv; elm-live src/Main.elm --path-to-elm=node_modules/.bin/elm --dir=public --pushstate --verbose --proxy-prefix=/api --proxy-host=${API_URL} -- --output public/bundle.js


> codebase-ui@1.0.0 makeElmEnv
> node ./scripts/makeElmEnv.mjs

sh: elm-live: command not found
npm notice 
npm notice New minor version of npm available! 7.0.14 -> 7.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.0
npm notice Run npm install -g npm@7.6.0 to update!
npm notice 
npm ERR! code 127
npm ERR! path /Users/arya/codebase-ui
npm ERR! command failed
npm ERR! command sh -c npm run makeElmEnv; elm-live src/Main.elm --path-to-elm=node_modules/.bin/elm --dir=public --pushstate --verbose --proxy-prefix=/api --proxy-host=${API_URL} -- --output public/bundle.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arya/.npm/_logs/2021-03-03T23_07_22_508Z-debug.log
arya@jrrr codebase-ui % 
```

I guess I need to install something Elm-related? But it would be great if the specifics could be added to the README when you have a chance.

Thanks in advance!

**Comment by aryairani** [comment]
Update: I tried `npm install elm-live`, and it did something but also complained of high severity vulnerabilities:

```
arya@jrrr codebase-ui % npm install elm-live
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 186 packages, and audited 186 packages in 4s

8 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
arya@jrrr codebase-ui %
```
Running `npm audit fix --force` as it suggests gives me an alternating list of 2 or 4 vulnerabilities (from `http-proxy <1.18.1` and sometimes `minimist <0.2.1 || >=1.0.0 <1.2.3`), and suggests I run the same command again.

Thanks in advance.

**Comment by aryairani** [comment]
Launching `npm start` again anyway:
```
arya@jrrr codebase-ui % API_URL="http://127.0.0.1:55484" API_TOKEN="X%2FkGfCrT2RUerJpU0x6bibwQsA0410dv" npm start

> codebase-ui@1.0.0 start
> npm run makeElmEnv; elm-live src/Main.elm --path-to-elm=node_modules/.bin/elm --dir=public --pushstate --verbose --proxy-prefix=/api --proxy-host=${API_URL} -- --output public/bundle.js


> codebase-ui@1.0.0 makeElmEnv
> node ./scripts/makeElmEnv.mjs

Starting downloads...

  ● elm/virtual-dom 1.0.2
  ● elm/core 1.0.5
  ● elm/http 2.0.0
  ● elm/bytes 1.0.8
  ● y0hy0h/ordered-containers 2.0.1
  ● elm/random 1.0.0
  ● elm/file 1.0.5
  ● elm/svg 1.0.1
  ● elm/json 1.1.3
  ● elm-community/list-extra 8.2.4
  ● elm/browser 1.0.2
  ● elm-community/json-extra 4.3.0
  ● elm/time 1.0.0
  ● elm/parser 1.1.0
  ● rtfeldman/elm-iso8601-date-strings 1.1.3
  ● elm/url 1.0.0
  ● krisajenkins/remotedata 6.0.1
  ● elm/html 1.0.0
  ● mgold/elm-nonempty-list 4.1.0
  ● elm-explorations/test 1.2.2
  ● stoeffel/set-extra 1.2.3

Dependencies ready!           
Success! Compiled 15 modules.

    Main ───> public/bundle.js


elm-live:
  The build has succeeded. Starting the server!


Reload web server:
  - Website URL: http://localhost:8000
  - Listening on port: 8000
  - Monitoring dir: public

elm-live:
  Watching src/**/*.elm.
```
I get a seemingly infinite series of
```
node:internal/fs/utils:814
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:1505:5)
    at Server.listener (/Users/arya/codebase-ui/node_modules/elm-serve/lib/elm-reload-server.js:93:8)
    at Object.onceWrapper (node:events:482:28)
    at Server.emit (node:events:388:22)
    at emitListeningNT (node:net:1324:10)
    at processTicksAndRejections (node:internal/process/task_queues:79:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
And browsing to http://localhost:8000/ gives me Connection Refused.

Please advise. 😅

**Comment by hojberg** [comment]
Running `npm install` before doing anything should ensure you have all the dependencies (I'll add that step to the readme).

Which version of node are you running? (`node -v`)

**Comment by aryairani** [comment]
```
arya@jrrr codebase-ui % node -v
v15.3.0
```

**Comment by aryairani** [comment]
When I first ran `npm start`, it told me 
```
New minor version of npm available! 7.0.14 -> 7.6.0
Changelog: https://github.com/npm/cli/releases/tag/v7.6.0
Run npm install -g npm@7.6.0 to update!
```
Eventually I ran that command; but I see now that npm != node.

**Comment by hojberg** [comment]
Hmmm that version of node should be fine...

**Comment by aryairani** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:1505:5)
    at Server.listener (/Users/arya/codebase-ui/node_modules/elm-serve/lib/elm-reload-server.js:93:8)
    at Object.onceWrapper (node:events:482:28)
    at Server.emit (node:events:388:22)
    at emitListeningNT (node:net:1324:10)
    at processTicksAndRejections (node:internal/process/task_queues:79:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
^C
arya@jrrr codebase-ui % npm install

up to date, audited 206 packages in 3s

8 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (1 low, 3 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
arya@jrrr codebase-ui % npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating elm-live to 4.0.2,which is a SemVer major change.

added 8 packages, removed 27 packages, changed 15 packages, and audited 187 packages in 2s

8 packages are looking for funding
  run `npm fund` for details

# npm audit report

http-proxy  <1.18.1
Severity: high
Denial of Service - https://npmjs.com/advisories/1486
fix available via `npm audit fix --force`
Will install elm-live@3.4.1, which is a breaking change
node_modules/http-proxy
  elm-live  >=4.0.0-alpha.9
  Depends on vulnerable versions of http-proxy
  node_modules/elm-live

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

arya@jrrr codebase-ui % API_URL="http://127.0.0.1:55484" API_TOKEN="X%2FkGfCrT2RUerJpU0x6bibwQsA0410dv" npm start

> codebase-ui@1.0.0 start
> npm run makeElmEnv; elm-live src/Main.elm --path-to-elm=node_modules/.bin/elm --dir=public --pushstate --verbose --proxy-prefix=/api --proxy-host=${API_URL} -- --output public/bundle.js


> codebase-ui@1.0.0 makeElmEnv
> node ./scripts/makeElmEnv.mjs


elm-live:
  Server has been started! Server details below:
    - Website URL: http://localhost:8000
    - Serving files from: public
    - Proxying requests starting with /api to http://127.0.0.1:55484

elm-live:
  The build has succeeded. 

elm-live:
  Watching the following files:
    - src/**/*.elm
```
I restarted it a third time and it worked?

**Comment by hojberg** [comment]
Oh maybe this was the audit fixes that messed something up. Those btw are safe to ignore right now. They do not have an affect on any production build. `elm-live` has an open issue to bump its dependency.

**Comment by hojberg** [comment]
I added more instructions to the README. Closing this.
